<?php
include("footerheader.php");
fHeader();
?>
<div class="col-12 d-flex align-items-center justify-content-between mt-3 mb-3">
  <div class="title"> Terms & Conditions </div>
</div>
<div class="container py-2 mb-3 bg-white">
  <p><b>1.</b> <b>Acceptance of these Terms and Conditions of Use</b></p>
  <p>These terms and conditions, together with any documents (including the Exhibits attached hereto) and additional terms they expressly incorporate by reference (collectively, these &ldquo;<b>Terms</b>&rdquo;), constitute a legal agreement and are entered into by and between you and Inventi Inc. (&ldquo;<b>Inventi</b>&rdquo;, &ldquo;<b>we</b>&rdquo;, &ldquo;<b>us</b>&rdquo; or &ldquo;<b>our</b>&rdquo;), a corporation organized under the laws of the province of Ontario.</p>
  <p>Inventi is the operator of www.Inventi.com (and any other sites accessible via subdomains of www.Inventi.com) (&ldquo;<b>Website</b>&rdquo;), our mobile applications (including, Haüskey: New Condo Real Estate) (&ldquo;<b>Mobile Apps</b>&rdquo;) and our assignment platform that we make generally available to the public, and which we may offer through our Website or Mobile Apps ( &ldquo;<b>Assignment Platform</b>&rdquo;). The These terms govern your access to and your use of any content and any Interactive Functions (as hereinafter defined) offered on or through our Website. Additional terms and conditions, as applicable and as expressly set forth in the Exhibits attached hereto, apply to your access and use of our Mobile Apps and our Assignment Platform.</p>
  <p>BY USING OUR WEBSITE, MOBILE APPS, OR ASSIGNMENT PLATFORM, YOU: (A) ACKNOWLEDGE THAT YOU HAVE READ AND UNDERSTAND THESE TERMS; (B) YOU ACCEPT AND AGREE TO BE BOUND TO AND COMPLY WITH THESE TERMS; (C) YOU REPRESENT AND WARRANT THAT YOU ARE THE LEGAL AGE OF MAJORITY FROM WHERE YOU ARE ACCESSING OR USING OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM, CAN FORM A LEGALLY BINDING CONTRACT ONLINE, AND HAVE THE FULL RIGHT, POWER AND AUTHORITY TO COMPLY WITH THE OBLIGATIONS UNDER THESE TERMS, AND IF YOU ARE ENTERING INTO THESE TERMS FOR AN ORGANIZATION OR OTHER ENTITY, THAT YOU HAVE THE LEGAL AUTHORITY TO BIND SUCH ORGANIZATION OR ENTITY. IF YOU DO NOT MEET ALL OF THE FOREGOING ELIGIBILITY REQUIREMENTS OR DO NOT AGREE TO ANY OF THESE TERMS, YOU MUST NOT ACCESS OR USE OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM.</p>
  <p><b>2.</b><b> Modifications to these Terms and our Website and Mobile Apps</b></p>
  <p>We reserve the right in our sole discretion to revise and update these Terms from time to time. Any and all such modifications are effective immediately upon posting and apply to all access to and continued use of our Website or Mobile Apps. You agree to periodically review these Terms in order to be aware of any such modifications. By continuing to access or use our Website or Mobile Apps following any modifications made to the Terms, you accept and agree to be bound to the modified Terms.</p>
  <p>The &ldquo;Last Updated&rdquo; date indicates when these Terms were last revised.</p>
  <p>We may in our sole discretion change, withdraw or terminate any of the content or Interactive Functions (as hereinafter defined) offered on or through our Website or Mobile Apps at any time without notice. We will not be liable, for any reason, if all or any part of our Website or Mobile Apps is restricted to users or unavailable at any time or for any period of time.</p>
  <p><b>3. </b><b>Inventi&rsquo;s Services</b></p>
  <p>Inventi is the operator of the Website, Mobile Apps and Assignment Platform. As the operator of the foregoing, <b>Inventi DOES NOT, AND DOES NOT INTEND TO, PROVIDE ANY REAL ESTATE ADVICE, REPRESENTATION, OR ANY SERVICES RELATING TO THE TRADE OF REAL ESTATE UNDER THESE TERMS (INCLUDING THROUGH THE OPERATION OF OR THE PERFORMANCE OF ANY SERVICES RELATING TO THE WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM)</b>.</p>
  <p>Without limiting the generality of the foregoing, you acknowledge that Inventi&rsquo;s affiliate, <b>Inventi Realty Inc.</b>, is licensed to trade real estate in Ontario. Further, you acknowledge and agree that our affiliate, <b>Inventi Realty Inc.</b>, may use our Website, Mobile Apps and Assignment Platform for marketing purposes, including, as a virtual office website.</p>
  <p>To the extent that you wish to receive any real estate advice, representation or any other services relating to the trade of real estate from Inventi or its affiliates, you acknowledge that you will be required to enter into a written agreement with our affiliate, <b>Inventi Realty Inc.</b>, for such services, and you acknowledge that the terms and conditions set forth in such agreement will govern the performance of such services by Inventi Realty Inc.</p>
  <p>You may find more information about Inventi Realty Inc. at the following <a href="https://Inventi.com/settings/settings/aboutUs" target="_blank">link</a>.</p>
  <p><b>4. </b><b>No Reliance</b></p>
  <p>The content on our Website or in our Mobile Apps is provided for general information purposes only. It is not intended to amount to advice on which you should rely. You must obtain more specific or professional advice before taking, or refraining from, any action or inaction on the basis of the content on our site.</p>
  <p>Although we make reasonable efforts to update any content that we provide on our Website or through our Mobile Apps, we make no representations, warranties or guarantees, whether express or implied, that the content on our Website or Mobile Apps is accurate, complete or up to date. Your use of our Website or Mobile Apps is at your own risk and neither Inventi nor its affiliates, nor their respective directors, officers, employees, agents, service providers, contractors, licensors, licensees, suppliers or successors (collectively, &ldquo;<b>Representatives</b>&rdquo;) have any responsibility or liability whatsoever for your use of our Website or Mobile Apps.</p>
  <p>Notwithstanding the immediately preceding paragraph, our Website and Mobile Apps may include or provide access to content provided by third parties, including any User Contributions (as hereinafter defined). All statements and/or opinions expressed in any such third-party content, other than content that is provided directly by us, are solely the opinions and the responsibility of the person or entity providing those materials. Such materials do not necessarily reflect the opinion of Inventi, its affiliates or any of their Representatives. Further, we do not have any responsibility or liability whatsoever to you, or any third party, for the content or accuracy of any such third-party materials.</p>
  <p><b>5. </b><b>Your Inventi Account</b></p>
  <p>Certain functionality on our Website or Mobile Apps requires you to complete our account registration process and to have a valid user account (a &ldquo;<b>Inventi Account</b>&rdquo;) in order to use such functionality. If you create or use any functionality that requires a Inventi Account, you agree that, in connection with your Inventi Account, you:</p>
  <p>(a) will not use any functionality that requires a Inventi Account for any purposes which are fraudulent, offensive, defamatory, obscene or otherwise unlawful;</p>
  <p>(b) will use any functionality that requires a Inventi Account in a manner that complies with all applicable laws, rules and regulations, and any other guidelines, standards and any other requirements that may be posted on our Website from time to time;</p>
  <p>(c) represent and warrant that any information in your Inventi Account is and will remain accurate, complete and valid, and you agree that you are solely responsible for maintaining the accuracy, completeness and validity of any such information at all times;</p>
  <p>(d) are responsible and liable for all uses of our Website, Mobile Apps or Assignment Platform resulting from access through your Inventi Account, whether or not provided by you, directly or indirectly, and whether such access or use is permitted by or in violation of these Terms;</p>
  <p>(e) acknowledge that any personal information that you provide to us while completing our account registration process or that is otherwise used in or through your Inventi Account will be governed by our Privacy Policy;</p>
  <p>(f) hereby grant to us, our affiliates, and our respective Representatives, a non-exclusive, royalty-free, worldwide licence to reproduce, distribute, modify and otherwise use any information or data that you provide to us through your Inventi Account;</p>
  <p>(g) agree that you: (i) are responsible for keeping your passwords and access credentials associated with your Inventi Account confidential; (ii) will not sell or transfer any of your passwords or access credentials to any other person or entity; and (iii) will notify us about any unauthorized access to your passwords or access credentials.</p>
  <p>We reserve the right at any time and from time to time, to disable or terminate your Inventi Account or your access to our Website, Mobile Apps or Assignment Platform, in our sole discretion for any or no reason whatsoever, including as a result of your violation of any of these Terms.</p>
  <p><br>
  </p>
  <p><b>6. </b><b>Your Use of our Website and Mobile Apps; Security</b></p>
  <p>The security of your personal information is very important to us. We use physical, electronic, and administrative measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure. However, the safety and security of your information also depends on you and how you access our Website or Mobile Apps, which will be your sole responsibility. Unfortunately, depending on how you access our Website or Mobile Apps, the transmission of information via the internet may not be completely secure. As a result, although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our Website or Mobile Apps. Any transmission of personal information is at your own risk.</p>
  <p>As a condition to accessing or using our Website, Mobile Apps or Assignment Platform, you agree to not:</p>
  <p>(a) access content and data that is not intended for you;</p>
  <p>(b) attempt to cause or cause the breach or circumvention of the security, privacy and/or authentication measures used on our Website or Mobile Apps, including, without limitation, attempting to use passwords or access credentials associated with user accounts other than your Inventi Account or other Inventi Accounts which you are authorized to use;</p>
  <p>(c) restrict, disrupt or disable our Website, Mobile Apps or Assignment Platform, or their functionality to users, hosts, servers or networks;</p>
  <p>(d) illicitly exploit data packet headers being transmitted between you and our Website, Mobile Apps or Assignment Platform;</p>
  <p>(e) disrupt network services used for or otherwise disrupt any abilities to monitor our Website, Mobile Apps or Assignment Platform;</p>
  <p>(f) use any robot, spider, or other automatic device, process, systems or means to access, use, or scrape, mine or otherwise extract data, from our Website, Mobile Apps or Assignment Platform for any purpose, including, but not limited to, monitoring or copying any of the materials or functionality from our Website, Mobile Apps or Assignment Platform;</p>
  <p>(g) introduce any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful to our Website, Mobile Apps or Assignment Platform;</p>
  <p>(h) attack our Website or Assignment Platform via a denial-of-service attack, distributed denial-of-service attack, flooding, mailbombing or crashing;</p>
  <p>(i) otherwise attempt to interfere with the proper working of our Website, Mobile Apps or Assignment Platform; and</p>
  <p>(j) access or use our Website, Mobile Apps or Assignment Platform for any purposes that violate applicable laws or in a manner that contravenes these Terms.</p>
  <p><br>
  </p>
  <p><b>7. </b><b>User Contributions</b></p>
  <p>Our Website, Mobile Apps and Assignment Platform may provide certain functionality that allows users to provide information and make submissions to us, such as, through any services, mobile applications, chat features, e-mail, message boards, profiles, forums, bulletin boards, customer service, feedback or suggestion forms, and other such functions that we may offer through our Website, Mobile Apps and Assignment Platform (collectively, &ldquo;<b>Interactive Functions</b>&rdquo;). You acknowledge and agree that your use of any Interactive Functions requires a Inventi Account and that, to the extent you access or use any Interactive Functions, such access or use must be done through your Inventi Account. Your use of any such Interactive Function constitutes your consent to all actions we take with respect to any information, submissions or other contributions that you submit, post, publish, display, or transmit to us (collectively, your &ldquo;<b>User Contributions</b>&rdquo;).</p>
  <p>In making or submitting a User Contribution through any such Interactive Functions, you agree that:</p>
  <p>(a) your User Contribution will not be subject to any confidentiality obligations owed by Inventi or our Representatives;</p>
  <p>(b) you grant to us, our subcontractors, and our respective licensees, successors, and assigns, a world-wide, royalty free, perpetual, irrevocable, non-exclusive licence to use, reproduce, modify, perform, display, distribute, and otherwise disclose to third parties your User Contribution without compensation to you;</p>
  <p>(c) as a condition of submitting your User Contribution, you waive any moral rights or other rights of authorship subsisting therein;</p>
  <p>(d) neither Inventi, its affiliates nor their respective Representatives will be responsible or liable for any of your User Contributions, and you will remain fully responsible and legally liable, including to any third party, for the contents and accuracy of your User Contribution; and</p>
  <p>(e) your User Contribution shall not:</p>
  <p>(i) violate any applicable federal, provincial, local or international law or regulation (including, without limitation, any laws regarding the export of data or software, patent, trademark, trade secret, copyright or other intellectual property, legal rights, or contain any materials that could give rise to any civil or criminal liability under such laws or regulations or that otherwise may conflict or violate these Terms or our Privacy Policy);</p>
  <p>(ii) infringe or misappropriate the intellectual property or proprietary rights of a third party;</p>
  <p>(iii) in any manner violate the terms of use of any third-party website that is linked to our Website or otherwise accessed through our Mobile Apps or Assignment Platform, including, but not limited to, any third-party social media website;</p>
  <p>(iv) include or contain any materials that is exploitive, obscene, harmful, threatening, abusive, harassing, hateful, defamatory, sexually explicit or pornographic, violent, inflammatory, or discriminatory based on race, sex, religion, nationality, disability, sexual orientation, or age, or other such legally prohibited ground, to be otherwise objectionable as determined by Inventi in its sole discretion;</p>
  <p>(v) involve, provide or contribute any false, inaccurate or misleading information;</p>
  <p>(vi) impersonate or attempt to impersonate Inventi, a Inventi employee, another user, or any other person or entity;</p>
  <p>(vii) transmit, or procure the sending of, any advertisements or promotions, sales, or encourage any other commercial activities without our prior written consent; or</p>
  <p>(viii) promote any illegal activity, or advocate, promote or assist any unlawful act.</p>
  <p>Without limiting the generality of the foregoing, by making a User Contribution through the use of any Interactive Functions, you represent and warrant that you own or have the necessary rights to submit your User Contribution and perform your obligations relating to your User Contribution hereunder.</p>
  <p><br>
  </p>
  <p><b>8.</b><b> Site Monitoring and Enforcement, Suspension and Termination</b></p>
  <p>Inventi has the right to, without prior notice to you: (a) remove or refuse to post on our Website or Assignment Platform any of your User Contributions for any or no reason in our sole discretion; (b) at all times, take such actions with respect to any of your User Contributions as we deem necessary or appropriate in our sole discretion, including, without limitation, for violating these Terms; (c) take appropriate legal action, including, without limitation, referral to law enforcement or regulatory authority, or notifying the harmed party of any illegal or unauthorized use of our Website, Mobile Apps or Assignment Platform, and fully cooperate with any such law enforcement or regulatory authority, or any court order, requesting or directing us to disclose the identity or other information relating to any of your User Contributions; or (d) terminate or suspend your access to all or part of our Website, Mobile Apps or Assignment Platform for any or no reason, including, without limitation, any violation of these Terms.</p>
  <p>YOU WAIVE AND HOLD HARMLESS Inventi, ITS AFFILIATES AND THEIR REPRESENTATIVES FROM ANY AND ALL CLAIMS RESULTING FROM ANY ACTION TAKEN BY Inventi AND ANY OF THE FOREGOING PARTIES RELATING TO ANY OF YOUR USER CONTRIBUTIONS, INCLUDING ANY INVESTIGATIONS OF OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM, OR YOUR USER CONTRIBUTIONS, BY Inventi, ITS AFFILIATES, OR ANY OF THEIR REPRESENTATIVES, OR BY LAW ENFORCEMENT AUTHORITIES.</p>
  <p>We have no obligation or responsibility to monitor our Website, Mobile Apps, Assignment Platform, or their use, and do not and cannot undertake to review materials that you or other users submit to our Website or Assignment Platform. We cannot ensure prompt removal of objectionable material after it has been posted.</p>
  <p>THEREFORE, TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, Inventi, ITS AFFILIATES, AND THEIR RESPECTIVE REPRESENTATIVES DISCLAIM ANY LIABILITY FOR ANY ACTION OR INACTION ARISING FROM OR RELATING TO TRANSMISSIONS, COMMUNICATIONS, OR CONTENT PROVIDED THROUGH OR ON OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM BY ANY USER OR THIRD PARTY.</p>
  <p><b>9. </b><b>Privacy</b></p>
  <p>By submitting your personal information with any User Contributions or otherwise providing us with any of your personal information, you consent to our collection, use, reproduction, hosting, transmission and disclosure of any of your personal information, as we deem necessary for the use of our Website, Mobile Apps or Services, in compliance with our privacy policy, which is located at: <a href="https://Inventi.com/settings/settings/privacy" target="_blank"><u>https://Inventi.com/settings/settings/privacy</u></a> (our &ldquo;<b>Privacy Policy</b>&rdquo;) and is incorporated into these Terms by reference.</p>
  <p><b>10. </b><b>Intellectual Property Rights and Ownership of Website</b></p>
  <p>You understand and agree that, as between us and you, our Website, Mobile Apps, Assignment Platform and their entire contents, features, and functionality, including, but not limited to, all information, software, code, text, displays, graphics, photographs, video, audio, design, presentation, selection, and arrangement, are owned by Inventi and are protected in all forms by intellectual property laws, including without limitation, copyright, trademark, patent, trade secret, and any other proprietary rights. All rights not expressly granted under these Terms are reserved by Inventi, its affiliates or their Representatives. You understand and agree that, as between you and us, you have no right, title or interest in our Website, Mobile Apps or Assignment Platform, or any of the materials on or in our Website, Mobile Apps or Assignment Platform, and that no such right, title or interest will transfer to you when you access or use our Website, Mobile Apps or Assignment Platform. You are not permitted to modify copies of any materials from our Website nor delete or alter any copyright, trademark, or other proprietary rights notices from copies of materials from this site.</p>
  <p>Inventi&rsquo;s name and logo, and all related names, logos, product and service names, designs, images and slogans are trademarks of Inventi or its affiliates. You must not use such marks without the prior written permission of Inventi.</p>
  <p>REALTOR®, REALTORS®, MLS®, Multiple Listing Service®, and any related logos or certification marks are owned or controlled by the Canadian Real Estate Association and the uses of any of the foregoing trademarks on our Website or in our Mobile Apps are done so under licence. Any other names, logos, product and service names, designs, images and slogans mentioned, or which appear on our Website or in our Mobile Apps are the trademarks of their respective owners. Use of any such property, except as expressly authorized, shall constitute an infringement or violation of the rights of the property owner and may be a violation of federal or other laws and could subject the infringer to legal action.</p>
  <p>Unless Inventi has provided its express written consent otherwise, you may only use our Website, Mobile Apps and Assignment Platform for your personal use. Further, you shall not directly or indirectly reproduce, compile for an internal database, distribute, modify, create derivative works of, frame, link to, mirror, publicly display, publicly perform, republish, download, store, or transmit any of the materials on our Website, Mobile Apps or Assignment Platform without our prior written consent, except as follows: (a) you may temporarily store or cache copies of such materials on your computer and browser; (b) you may print a reasonable number of copies of such materials for personal use only, provided that you keep any proprietary notices thereon, and only use such copies for non-commercial and lawful personal use and not for further reproduction, publication, or distribution of any kind on any medium whatsoever; and (c) to the extent any content or Interactive Functions on or in our Website, Mobile Apps or Assignment Platform are linked to or use any social media platforms, you may only use such content and Interactive Functions in accordance with these Terms and as such third-party social media platforms permit.</p>
  <p>You may not frame our Website on any other site or create a link to any part of our Website, except for our home page (<a href="https://www.Inventi.com/" target="_blank"><u>www.Inventi.com</u></a>) without our prior written consent. Further, where such consent is granted, we reserve the right to revoke any such linking permission without notice. You agree to cooperate with us in causing any unauthorized framing or linking to immediately stop.</p>
  <p>If you print off, copy or download any part of our Website in breach of these Terms, your right to use our Website and Mobile Apps will cease immediately and you must, at our option, return or destroy any copies of the materials you have made.</p>
  <p><b>11. </b><b>Third Party Websites</b></p>
  <p>For your convenience, our Website, Mobile Apps or Assignment Platform may provide links or pointers to third-party sites. We make no representations about any other websites that may be accessed from our Website, Mobile Apps or Assignment Platform. If you choose to access any such sites, you do so at your own risk. We have no control over the contents of any such third-party sites (including, for certainty, social media platforms) and accept no responsibility for such sites or for any loss or damage that may arise from your use of them. To the extent our Website, Mobile Apps or Assignment Platform provide links or pointers to third-party sites, your use of such links or pointers is subject to the respective third-party site&rsquo;s terms and conditions.</p>
  <p><b>12. </b><b>Disclaimers</b></p>
  <p>YOU UNDERSTAND AND AGREE THAT YOUR USE OF OUR WEBSITE, MOBILE APPS, ASSIGNMENT PLATFORM, AND THEIR CONTENTS, THE INTERACTIVE FUNCTIONS AND ANY ITEMS FOUND OR ATTAINED THROUGH OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM IS AT YOUR OWN RISK. OUR WEBSITE, MOBILE APPS, ASSIGNMENT PLATFORM AND THEIR CONTENTS, THE INTERACTIVE FUNCTIONS AND ANY ITEMS FOUND OR ATTAINED THROUGH OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM ARE PROVIDED ON AN &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; BASIS, WITHOUT ANY REPRESENTATIONS, WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.</p>
  <p>NEITHER Inventi NOR ITS AFFILIATES, NOR THEIR RESPECTIVE REPRESENTATIVES, MAKE ANY REPRESENTATIONS, WARRANTIES, CONDITIONS OR ENDORSEMENTS WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, SUITABILITY, ACCURACY, CURRENCY OR AVAILABILITY OF OUR WEBSITE, MOBILE APPS, ASSIGNMENT PLATFORM, OR THEIR CONTENTS, OR THE INTERACTIVE FUNCTIONS. WITHOUT LIMITING THE FOREGOING, NEITHER Inventi NOR ITS AFFILIATES, NOR THEIR RESPECTIVE REPRESENTATIVES, PROVIDE ANY REPRESENTATIONS, WARRANTIES OR CONDITIONS THAT OUR WEBSITE, MOBILE APPS, ASSIGNMENT PLATFORM, OR THEIR CONTENTS, THE INTERACTIVE FUNCTIONS OR ANY ITEMS FOUND OR ATTAINED THROUGH OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT ANY DEFECTS WILL BE CORRECTED, THAT OUR WEBSITE, MOBILE APPS, ASSIGNMENT PLATFORM OR THE SERVER(S) THAT MAKES THEM AVAILABLE, ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</p>
  <p>WE CANNOT AND DO NOT PROVIDE ANY GUARANTEES, REPRESENTATIONS, WARRANTIES OR CONDITIONS THAT FILES OR DATA AVAILABLE FOR DOWNLOADING FROM THE INTERNET, OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM WILL BE FREE OF VIRUSES OR OTHER DESTRUCTIVE CODE. YOU ARE SOLELY AND ENTIRELY RESPONSIBLE FOR YOUR USE OF OUR WEBSITE, MOBILE APPS, ASSIGNMENT PLATFORM, AND YOUR COMPUTER, INTERNET AND DATA SECURITY. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY DENIAL-OF-SERVICE ATTACK, DISTRIBUTED DENIAL-OF-SERVICE ATTACK, OVERLOADING, FLOODING, MAILBOMBING OR CRASHING, VIRUSES, TROJAN HORSES, WORMS, LOGIC BOMBS, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF OUR WEBSITE, MOBILE APPS, OR ASSIGNMENT PLATFORM, OR ITEMS FOUND OR ATTAINED THROUGH OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM, OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON THEM, OR ON ANY WEBSITE LINKED TO OR ACCESSED THROUGH OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM.</p>
  <p>THE LAWS OF CERTAIN JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LEGAL REPRESENTATIONS OR WARRANTIES. TO THE EXTENT THESE LAWS APPLY TO YOU, SOME OR ALL OF THE EXCLUSIONS OR LIMITATIONS ABOVE MAY NOT APPLY TO YOU, AND YOU MAY HAVE ADDITIONAL RIGHTS.</p>
  <p><b>13. </b><b>Limitation on Liability</b></p>
  <p>UNDER NO CIRCUMSTANCE WILL Inventi NOR ITS AFFILIATES, NOR THEIR RESPECTIVE REPRESENTATIVES, BE LIABLE FOR NEGLIGENCE, GROSS NEGLIGENCE, NEGLIGENT MISREPRESENTATION, FUNDAMENTAL BREACH, DAMAGES OF ANY KIND, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, PUNITIVE OR SIMILAR DAMAGES OR LIABILITIES WHATSOEVER (INCLUDING, BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA) ARISING OUT OF OR IN CONNECTION WITH OUR WEBSITE, MOBILE APPS, ASSIGNMENT PLATFORM OR ANY OTHER THIRD-PARTY WEBSITES LINKED TO OUR WEBSITE, MOBILE APPS OR ASSIGNMENT PLATFORM, OR ANY CONTENT, FUNCTIONALITY, USER CONTRIBUTIONS OR OTHER INFORMATION CONTAINED THEREON OR THEREIN, WHETHER UNDER TORT (INCLUDING NEGLIGENCE), CONTRACT, CIVIL LIABILITY, STATUTE, STRICT LIABILITY OR UNDER ANY OTHER THEORY OF LIABILITY, AND WHETHER OR NOT WE, OUR AFFILIATES OR OUR RESPECTIVE REPRESENTATIVES HAVE BEEN ADVISED OF, KNEW OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES.</p>
  <p><b>14. </b><b>Indemnification</b></p>
  <p>To the maximum extent permitted by applicable law, you agree to defend, indemnify, and hold harmless Inventi, its affiliates and their Representatives from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys&rsquo; fees) arising out of or relating to your breach of these Terms or your use of our Website, Mobile Apps or Assignment Platform, including, but not limited to, your User Contributions, your use of third-party sites linked to our Website or accessed through our Mobile Apps, and your use of our Website&rsquo;s or our Mobile Apps&rsquo; contents or Interactive Functions, other than as expressly authorized in these Terms.</p>
  <p><b>15. </b><b>Force Majeure</b></p>
  <p>In no event will we be liable or responsible to you, or be deemed to have defaulted under or been in breach of these Terms for any failure or delay in providing our Website, Mobile Apps or Assignment Platform to you, when and to the extent such failure or delay is caused by or results from acts beyond our reasonable control.</p>
  <p><b>16. </b><b>Interpretation</b></p>
  <p>For purposes of these Terms: (a) the words &ldquo;include&rdquo;, &ldquo;includes&rdquo; and &ldquo;including&rdquo; are deemed to be followed by the words &ldquo;without limitation&rdquo;; (b) the word &ldquo;or&rdquo; is not exclusive; (c) the words &ldquo;herein&rdquo;, &ldquo;hereof&rdquo;, &ldquo;hereby&rdquo;, &ldquo;hereto&rdquo; and &ldquo;hereunder&rdquo; refer to these Terms as a whole; (d) words denoting the singular have a comparable meaning when used in the plural, and vice-versa; (e) words denoting any gender include all genders; and (f) the headings under these Terms are for reference only and shall not affect the interpretation of these Terms. Unless the context otherwise requires, references in these Terms to sections, exhibits or other attachments means the sections of, and exhibits and attachments attached to, these Terms. These Terms shall be construed without regard to any presumption or rule requiring construction or interpretation against Inventi, as the party drafting an instrument or causing any instrument to be drafted.</p>
  <p><b>17. </b><b>Governing Law and Jurisdiction</b></p>
  <p>Our Website, Mobile Apps, Assignment Platform and these Terms will be governed by and construed in accordance with the provincial laws of Ontario and the federal laws of Canada applicable therein, without giving effect to any choice or conflict of law provision, principle or rule (whether of the provincial laws of Ontario or any other jurisdiction) and notwithstanding your domicile, residence or physical location.</p>
  <p>Any action or proceeding arising out of or relating to our Website, Mobile Apps, Assignment Platform and under these Terms will be instituted in the courts of the province of Ontario and/or the Federal Court of Canada, and each party irrevocably submits to the exclusive jurisdiction of such courts in any such action or proceeding. You waive any and all objections to the exercise of jurisdiction over you by such courts and to the venue of such courts.</p>
  <p><b>18. </b><b>Relationship of Parties; No Third Party Beneficiaries</b></p>
  <p>Nothing in these Terms shall be construed as creating any agency, partnership, joint venture or other form of joint enterprise, employment or fiduciary relationship between us and you, and neither party shall have authority to contract for or bind the other party in any manner whatsoever. This agreement is for the sole benefit of the parties and their respective assigns. Nothing under these Terms, express or implied, is intended to or shall confer upon any other person any legal or equitable right, benefit or remedy of any nature whatsoever under or by reason of these Terms.</p>
  <p><b>19. </b><b>Waiver</b></p>
  <p>No failure to exercise, or delay in exercising, any right, remedy, power or privilege arising from these Terms operates, or may be construed, as a waiver thereof. No single or partial exercise of any right, remedy, power or privilege hereunder precludes any other or further exercise thereof or the exercise of any other right, remedy, power or privilege.</p>
  <p><b>20. </b><b>Severability</b></p>
  <p>If any term or provision of these Terms is invalid, illegal or unenforceable in any jurisdiction, such invalidity, illegality or unenforceability shall not affect any other terms or provisions of these Terms or invalidate or render unenforceable such term or provision in any other jurisdiction.</p>
  <p><b>21. </b><b>Entire Agreement</b></p>
  <p>These Terms, the exhibits attached to these Terms, and our Privacy Policy constitute the sole and entire agreement between you and Inventi regarding our Website, Mobile Apps, Assignment Platform, their contents and the Interactive Functions, and supersedes all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, regarding such subject matter.</p>
  <p><b>22. </b><b>Reporting and Contact</b></p>
  <p>Our Website, Mobile Apps and Assignment Platform are operated by Inventi Inc., 79 Wellington St. W. #1620, Toronto, Ontario M5K1B1.</p>
  <p>Should you become aware of misuse of our Services, Website or Mobile Apps, including libelous or defamatory conduct, you must report it to Inventi at: privacy@Inventi.com. </p>
  <p>All other feedback, comments, requests for technical support (including, in connection to any defects or performance issues in our Mobile Apps), complaints, and other communications relating to our Website, Mobile Apps or Services should be directed to: info@Inventi.com.</p>
  <p><br>
  </p>
  <p> </p>
  <p><b><u>EXHIBIT A: ASSIGNMENT PLATFORM TERMS</u></b></p>
  <p><b>1. </b><b>Definitions.</b></p>
  <p>For the purposes of this Exhibit A, the following capitalized terms will have the applicable meanings as set forth below:</p>
  <p>(a) &ldquo;<b>APS</b>&rdquo; means an agreement of purchase and sale of the unit of a preconstruction condominium property, as described therein (each such property, a &ldquo;<b>Property</b>&rdquo;), between: (1) the relevant developer or builder (or beneficial owner and titleholder) of such property; and (2) the purchaser of such Property.</p>
  <p>(b) &ldquo;<b>Assignment Listing</b>&rdquo; has the meaning set out in Section 2(a) of this Exhibit A.</p>
  <p>(c) &ldquo;<b>Assignment Transaction</b>&rdquo; means any prospective, proposed or contemplated assignment transaction between a Buyer and Seller, whereby Seller assigns to Buyer, and Buyer assumes, all of Seller&rsquo;s obligations, rights and interests under an APS concerning a Property listed in an Assignment Listing.</p>
  <p>(d) &ldquo;<b>Buyer</b>&rdquo; means an end user on the Assignment Platform that wishes to enter into an assignment transaction to assume all obligations, rights and interests under an APS (including, the interests to the Property described therein) from a prospective seller.</p>
  <p>(e) &ldquo;<b>Property</b>&rdquo; has the meaning as set out in the definition for &ldquo;<b>APS</b>&rdquo;.</p>
  <p>(f) &ldquo;<b>Realtor</b>&rdquo; means any real estate agent or brokerage who is acting on behalf of a Buyer or Seller in connection with an Assignment Transaction.</p>
  <p>(g) &ldquo;<b>Secure Document Platform</b>&rdquo; has the meaning set out in Section 6 of this Exhibit A.</p>
  <p>(h) &ldquo;<b>Seller</b>&rdquo; means an end user on the Assignment Platform that has entered into a duly executed APS, between such end user and the relevant developer or builder (or beneficial owner and titleholder) of such property, for the purchase of the Property described therein, who wishes to assign their rights, obligations and interests under the APS from a prospective buyer.</p>
  <p>(i) &ldquo;<b>Services</b>&rdquo; has the meaning set out in Section 2 of this Exhibit A.</p>
  <p><br>
  </p>
  <p><b>2. </b><b>Services</b></p>
  <p>We provide the following functionality and services through our Assignment Platform (the &ldquo;<b>Services</b>&rdquo;):</p>
  <p>(a) qualified Sellers may submit a listing of their Property (in which they have an interest) on the Assignment Platform for the purpose of marketing that such Property is make generally available to the public for assignment (each, an &ldquo;<b>Assignment Listing</b>&rdquo;) in accordance with the terms and conditions set out in Section 3 of this Exhibit A;</p>
  <p>(b) end users of the Assignment Platform may view approved Assignment Listings in accordance with the terms and conditions set out in Section 4 of this Exhibit A;</p>
  <p>(c) qualified Buyers may submit a bid for a Property in an Assignment Listing in accordance with the terms and conditions set out in Section 5 of this Exhibit A; and</p>
  <p>(d) functionality for qualified users, and their agents and representatives, to securely prepare documents required to complete a transaction for the assignment of a preconstruction condominium as described in an approved Assignment Listing and to facilitate the completion of an Assignment Transaction on the Assignment Platform, both in accordance with the terms and conditions set out in Section 6 of this Exhibit A.</p>
  <p>To the extent that you use any of the Services listed above, the provisions of this Exhibit A will apply. BY USING THE SERVICES, YOU AGREE TO THE TERMS AND CONDITIONS SET FORTH IN THIS EXHIBIT A. IF YOU DO NOT AGREE TO ANY OF THE TERMS SET FORTH IN THIS EXHIBIT A, YOU MUST NOT ACCESS OR USE OUR SERVICES.</p>
  <p><b>3. </b><b>Submission of Assignment Listings</b></p>
  <p>If you, as a Seller on the Assignment Platform, submit a request to post an Assignment Listing for a Property on the Assignment Platform:</p>
  <p>(a) you acknowledge that the posting of an Assignment Listing is limited to Properties located in Ontario, Canada, and therefore represent that the Property that you wish to post in an Assignment Listing is located in Ontario, Canada ;</p>
  <p>(b) you agree that you will be required to complete the applicable Assignment Listing submission process in the Assignment Platform and you further agree that any information that is submitted as a part of such process may be shared with our licensed affiliate, <b>Inventi Realty, Inc.</b>;</p>
  <p>(c) you authorize us, and our affiliate, <b>Inventi Realty, Inc.</b>, to obtain credit reports about you from time to time for the purpose of confirming and verifying:</p>
  <p>(i) your identity, legal authorizations, certifications, in order for us to comply with applicable laws, such as the <em>Proceeds of Crime (Money Laundering) and Terrorist Financing Act</em> (Canada); and</p>
  <p>(ii) your legal authorizations, certifications, permissions, obligations or rights relating to the Property that you wish to post in an Assignment Listing;</p>
  <p>(d) you consent to making the Assignment Listing (and the information therein) generally available to the public on our Assignment Platform for marketing purposes and for any other purposes which we notify you of</p>
  <p>(e) you agree that Inventi or its affiliates are entitled to and may receive a finder&rsquo;s fee, reward and/or referral incentive and you consent to any such benefit being conferred to Inventi or its affiliates in connection with or as a result of the posting of a relevant Assignment Listing on the Assignment Platform or the closing of an Assignment Transaction; and</p>
  <p>(f) you represent, warrant and covenant to us that you:</p>
  <p>(i) are either:</p>
  <p>A. not represented by a Realtor in connection with a prospective Assignment Transaction involving the Property that you wish to post in an Assignment Listing, and have or will enter into a representation agreement with Inventi&rsquo;s affiliate, <b>Inventi Realty Inc.</b>, to serve as your Realtor in connection with any Assignment Transaction involving such Property; or</p>
  <p>B. are represented by a Realtor, but have or will entered into a co-operation agreement with Inventi&rsquo;s affiliate, <b>Inventi Realty Inc.</b>, in connection with the assignment of the Property that you wish to post in an Assignment Listing;</p>
  <p>(ii) are using the Assignment Platform solely for your own personal use and for non-commercial purposes;</p>
  <p>(iii) are not a Realtor or, if you are a Realtor, are not posting an Assignment Listing in a professional capacity or on behalf of a third party individual;</p>
  <p>(iv) will not make any false, misleading or deceptive representations regarding any Property that you wish to list in an Assignment Listing;</p>
  <p>(v) will provide true, accurate and complete information and documentation relating to any Property that you wish to list in an Assignment Listing to Inventi upon Inventi&rsquo;s reasonable request; and</p>
  <p>(vi) own or otherwise have, and will have, the necessary rights and consents to complete an Assignment Transaction involving any Property that you wish to list in an Assignment Listing.</p>
  <p>Without limiting the generality of the foregoing, you agree that we reserve the right to determine, in our sole discretion, whether to approve an Assignment Listing request, and that Inventi may revoke any such approval or remove any of your Assignment Listings on the Assignment Platform at any time and for any reason whatsoever, including as a result of: (1) you refusing to enter into a representation agreement with <b>Inventi Realty Inc.</b> or refusing to engage in a private sale; (2) your Realtor failing to enter into or otherwise terminating a co-operation agreement between your Realtor and our affiliate, <b>Inventi Realty Inc.</b>; or (3) your breach of these Terms or any of the terms and conditions set forth in this Exhibit A.</p>
  <p>Upon our approval of your Assignment Listing request, we will make reasonable efforts to post your Assignment Listing on the Assignment Platform.</p>
  <p><b>4. </b><b>Viewing Assignment Listings</b></p>
  <p>As a prospective Buyer on the Assignment Platform, you may view the Assignment Listings thereon. However, you acknowledge that some information in the Assignment Listing may only be available to you when you are using the Assignment Platform while logged onto your Inventi Account.</p>
  <p><b>5. </b><b>Bid Submissions on Assignment Listings</b></p>
  <p>As a precondition to making a bid on an Assignment Listing as a Buyer, you represent and warrant that you:</p>
  <p>(a) are not a party to an agreement with a Realtor to represent you in an Assignment Transaction involving the applicable Property listed in such Assignment Listing;</p>
  <p>(b) will not owe any fees, commissions, reward, incentives or any other benefits to any Realtors if you enter into a representation agreement with Inventi&rsquo;s affiliate, <b>Inventi Realty Inc.</b>, including, as a result of any holdover obligations in a terminated or expired representation agreement between you and a Realtor;</p>
  <p>(c) are using the Assignment Platform solely for your own personal use and for non-commercial purposes;</p>
  <p>(d) are not a Realtor or, if you are a licensed Realtor, are not making a bid in a professional capacity or on behalf of a third party individual;</p>
  <p>(e) will not make any false, misleading or deceptive representations regarding any bids that you make on an Assignment Listing; and</p>
  <p>(f) have obtained or will obtain all licenses, authorizations, approvals, consents or permits as may be required under applicable law or under an applicable APS in order to close an Assignment Transaction.</p>
  <p>Without limiting the generality of the foregoing, you agree that we reserve the right to remove or revoke, in our sole discretion, any of your bids on an Assignment Listing that you make on the Assignment Platform for any reason whatsoever, including as a result of your breach of these Terms or any of the terms and conditions set forth in this Exhibit A</p>
  <p><b>6. </b><b>Secure Document Platform</b></p>
  <p>Inventi will use reasonable efforts to provide online tools on the Assignment Platform (collectively, the &ldquo;<b>Secure Document Platform</b>&rdquo;) to facilitate an Assignment Transaction, including tools that allow you, as either a Buyer or Seller to: (a) upload, review, modify documents relating to an Assignment Transaction with your respective Realtors and professional agents; (b) electronically deliver any such documents to the counterparty of the Assignment Transaction; or (c) electronically execute such documents.</p>
  <p>To the extent any of your respective Realtors or professional agents wish to use any online tools on your behalf for any of the purposes described in the preceding paragraph, you agree that such Realtors and agents will be required to create a Inventi Account and that you will be required to authorize such Realtors and agents in order for them to access the Secure Document Platform. Further, in addition to the disclaimers set forth in Section 12 of the main body of these Terms, unless and to the extent otherwise agreed upon under a duly executed agreement, you agree that Inventi will not be responsible or liable to you for your actions, or any of your Realtor&rsquo;s or professional agent&rsquo;s actions made on your behalf, on the Secure Document Platform.</p>
  <p><b>7. </b><b>Account</b></p>
  <p>You must have a Inventi Account in order to use the Services and you agree that you will only use the Services through your Inventi Account.</p>
  <p><b>8. </b><b>Suspension or Termination of Services</b></p>
  <p>Without limiting any of our other rights or remedies, whether at law, in equity or under these Terms, you agree that we may, directly or indirectly, suspend, terminate or otherwise deny your access to or your use of all or any part of the Services, without incurring any resulting obligations or liability, if:</p>
  <p>(a) we receive a governmental or court order that expressly or by reasonable implication requires us to do so; or</p>
  <p>(b) we believe, in our sole discretion, that you have failed to comply with any material terms or conditions of these Terms or this Exhibit A or that you are, have been, or are likely to be involved in any fraudulent, misleading or unlawful activities.</p>
  <p><b>9. </b><b>Subcontractors</b></p>
  <p>We may, from time to time, and in our sole discretion, engage third parties (including, for certainty, our Representatives) to perform all or portions of the Services.</p>
  <p><b>10. </b><b>Limitation of Liability: The Assignment Platform</b></p>
  <p>UNLESS AND TO THE EXTENT OTHERWISE AGREED UPON UNDER A DULY EXECUTED AGREEMENT, AND EXCEPT TO THE EXTENT SUCH EXCLUSIONS ARE PROHIBITED BY LAW, NEITHER Inventi NOR ITS REPRESENTATIVES WILL BE LIABLE TO YOU, YOUR PROFESSIONAL REPRESENTATIVES, OR ANY OTHER PERSON FOR ANY NEGLIGENCE, GROSS NEGLIGENCE, NEGLIGENCE MISREPRESENTATION, FUNDAMENTAL BREACH OR DAMAGES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THE SERVICES OR ANY ASSIGNMENT TRANSACTIONS, WHETHER UNDER TORT, CONTRACT, OR ANY OTHER THEORY OF LIABILITY, AND WHETHER Inventi OR ITS REPRESENTATIVES HAVE BEEN ADVISED OF, KNEW OF OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. FURTHER, OUR AGGREGATE LIABILITY ARISING OUT OF YOUR USE OF THE ASSIGNMENT PLATFORM WILL NOT EXCEED 100$ IN CONNECTION WITH ANY OF THE SERVICES RELATING TO THE ASSIGNMENT PLATFORM, WHICH GAVE RISE TO THE CLAIM.</p>
  <p><b>11.</b><b> Indemnification</b></p>
  <p>To the maximum extent permitted by applicable law, you agree to defend, indemnify, and hold harmless Inventi, its affiliates and their respective Representatives, from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses or fees (including reasonable attorneys&rsquo; fees) arising out of your breach of any of the terms and conditions applicable to you under this Exhibit A or in connection with your use of the Services or arising from any Assignment Transaction to which you are a party that is being or has been facilitated through the Assignment Platform.</p>
  <p><br>
  </p>
  <p><b><u>EXHIBIT B: IOS MOBILE APPS</u></b></p>
  <p>In addition to these Terms, the following provisions apply with respect to your use of any versions of our Mobile Apps that operate on the iOS operating system (our &ldquo;<b>iOS Mobile Apps</b>&rdquo;), as made available by Apple Inc. (&ldquo;<b>Apple</b>&rdquo;) on the iTunes App Store:</p>
  <p>(a) You acknowledge that any capitalized terms used in this Exhibit A, which are not defined under these Terms, shall have the meanings as given to such terms in Apple&rsquo;s applicable terms and conditions;</p>
  <p>(b) You agree that Apple is not a party to these Terms and is not responsible for any of our Mobile Apps;</p>
  <p>(c) We hereby grant to you a non-transferrable, limited licence to use iOS Mobile Apps in accordance with these Terms and solely on any Apple-branded Products that you own or control, and as permitted by the Usage Rules set forth in the App Store Terms of Service, except that such iOS Apps may be accessed and used by other accounts associated with the purchaser via Family Sharing or volume purchasing;</p>
  <p>(d) You agree that Apple:</p>
  <p>(i) has no obligation whatsoever to furnish any maintenance and support services with respect to our iOS Mobile Apps;</p>
  <p>(ii) does not provide any product warranties, whether express or implied by law, to the extent not effectively disclaimed, to our iOS Mobile Apps except, if applicable, solely to the refund of the purchase price for our iOS Mobile Apps;</p>
  <p>(iii) to the maximum extent permitted by applicable law, has no other warranty obligations whatsoever with respect to our iOS Mobile Apps (other than as expressly set out in the immediately preceding item (ii)), and any other claims (including, arising from our iOS Mobile Apps infringing on or otherwise violating any third-party&rsquo;s intellectual property rights), losses, liabilities, damages, costs or expenses attributable to any failure to conform to any warranty that we provide to you under these Terms;</p>
  <p>(iv) is not responsible for addressing any of your or any third-party claims relating to our iOS Mobile Apps, including but not limited to:</p>
  <p>A. product liability claims;</p>
  <p>B. any claims that our iOS Mobile Aps fail to conform to any applicable legal or regulatory requirement; and</p>
  <p>C. claims arising under consumer protection, privacy, or similar legislation, including to the extent our iOS Mobile Apps&rsquo; uses of the HealthKit and HomeKit frameworks;</p>
  <p>(e) You represent and warrant that:</p>
  <p>(i) you are not located in a country that is subject to a U.S. Government embargo, or that has been designated by the U.S. Government as a &ldquo;terrorist supporting&rdquo; country; and</p>
  <p>(ii) you are not listed on any U.S. Government list of prohibited or restricted parties; and</p>
  <p>(f) You acknowledge and agree that Apple, and its subsidiaries, are third party beneficiaries to our Terms, and that, upon your acceptance of our Terms, Apple will have the right (and will be deemed to have accepted the right) to enforce these Terms against you as a third party beneficiary thereof.</p>
  <p><br>
  </p>
  <p><b><u>EXHIBIT C: ANDROID MOBILE APPS</u></b></p>
  <p>In addition to these Terms, the following provisions apply with respect to your use of any versions of our Mobile Apps that operate on the Android operating system (our &ldquo;<b>Android Mobile Apps</b>&rdquo;), as made available by Google LLC (&ldquo;<b>Google</b>&rdquo;) on the Google Play Store:</p>
  <p>(a) You acknowledge that any capitalized terms used in this Exhibit A, which are not defined under these Terms, shall have the meanings as given to such terms in Google&rsquo;s applicable terms and conditions;</p>
  <p>(b) You acknowledge and agree that Google is not a party to these Terms, and will not be responsible for, and will not have any liability under these Terms, including for our Android Mobile Apps;</p>
  <p>(c) We hereby grant to you (and, if applicable, any family members in your family group on Google Play) a non-exclusive, worldwide, perpetual and limited licence to perform, display and use our Android Mobile Apps in accordance with these Terms and Google&rsquo;s Google Play Terms of Service;</p>
  <p>(d) You agree that nothing under these Terms creates any liability for or has an adverse impact on Google or its Authorized Providers;</p>
  <p>(e) You acknowledge that you may be required to provide personal information, to us through our Android Mobile App, including any usernames, password, or other login information, and our use, collection, disclosure and processing of such personal information will be governed by our Privacy Policy;</p>
  <p>(f) If applicable, and where available, you may be entitled to a refund for our Android Mobile App from Google through the Google Play Store; and</p>
  <ul>
    <li>(g) You covenant to us that you will not use our Android Mobile Apps to generate or facilitate the generation of ID cards, social security numbers, passports, diplomas, credit cards, driver&rsquo;s licences, or in any other manner to mislead, deceive, slander or defame any other person.</li>
  </ul>
</div>
<?=fFooter();?>